# Generated by Django 4.1.7 on 2023-03-27 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=70, unique=True)),
                ('address', models.CharField(max_length=250)),
                ('photo', models.ImageField(blank=True, upload_to='profilepic')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee.designation')),
            ],
        ),
    ]
